name: "Raccoon HAP Bridge"
version: "0.1.0"
slug: "raccoon_hap_bridge"
description: "HomeKit HAP NodeJS Bridge"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
options:
  devices: []
schema:
  devices:
    type: list
    name: Device
    description: "Add Homekit device"
    items:
      type: dict
      keys:
        name:
          type: string
          required: true
          description: "Device name"
        type:
          type: select
          required: true
          name: Device typ
          options:
            - OTHER
            - BRIDGE
            - FAN
            - GARAGE_DOOR_OPENER
            - LIGHTBULB
            - DOOR_LOCK
            - OUTLET
            - SWITCH
            - THERMOSTAT
            - SENSOR
            - SECURITY_SYSTEM
            - DOOR
            - WINDOW
            - WINDOW_COVERING
            - PROGRAMMABLE_SWITCH
            - RANGE_EXTENDER
            - CAMERA
            - VIDEO_DOORBELL
            - AIR_PURIFIER
            - AIR_HEATER
            - AIR_CONDITIONER
            - AIR_HUMIDIFIER
            - AIR_DEHUMIDIFIER
            - APPLE_TV
            - HOMEPOD
            - SPEAKER
            - AIRPORT
            - SPRINKLER
            - FAUCET
            - SHOWER_HEAD
            - TELEVISION
            - TARGET_CONTROLLER
            - ROUTER
            - AUDIO_RECEIVER
            - TV_SET_TOP_BOX
            - TV_STREAMING_STICK
